<script setup lang="ts">
import { computed } from 'vue'
import {
  ArrowUpRight,
  ArrowRight,
  Search,
  Plus,
  LayoutGrid,
  Network,
  Settings2,
  ScrollText,
  RefreshCw,
  Copy,
  Star,
  Box,
  Globe,
  Database,
  Terminal,
  Monitor,
  ChevronRight,
  X,
  Menu,
  Check,
  ShieldCheck,
  Layers,
  Radio,
  Ellipsis,
  ExternalLink,
} from 'lucide-vue-next'
const props = withDefaults(defineProps<{ name: string; size?: number }>(), { size: 18 })
const icons: Record<string, typeof Box> = {
  ArrowUpRight,
  ArrowRight,
  Search,
  Plus,
  LayoutGrid,
  Network,
  Settings2,
  ScrollText,
  RefreshCw,
  Copy,
  Star,
  Box,
  Globe,
  Database,
  Terminal,
  Monitor,
  ChevronRight,
  X,
  Menu,
  Check,
  ShieldCheck,
  Layers,
  Radio,
  Ellipsis,
  ExternalLink,
}
const component = computed(() => icons[props.name] || Box)
</script>
<template><component :is="component" :size="size" :stroke-width="1.7" aria-hidden="true" /></template>
