import { test, expect, type Page } from '@playwright/test'
async function fillProxy(page: Page, name: string, port: string) {
  await page.getByRole('textbox', { name: '代理名称', exact: true }).fill(name)
  await page.getByRole('textbox', { name: '本地地址', exact: true }).fill('127.0.0.1')
  await page.getByLabel('本地端口', { exact: true }).fill('8080')
  await page.getByLabel('远程端口', { exact: true }).fill(port)
  await page.getByRole('textbox', { name: '显示名称', exact: true }).fill('测试服务')
}
test.beforeEach(async ({ request }) => {
  expect((await request.post('/__test/reset')).ok()).toBeTruthy()
})
test('launcher is local-only, searchable and protocol-aware', async ({ page }, info) => {
  const external: string[] = []
  const errors: string[] = []
  page.on('request', (r) => {
    if (!r.url().startsWith('http://127.0.0.1:18080')) external.push(r.url())
  })
  page.on('pageerror', (e) => errors.push(e.message))
  await page.goto('/')
  await expect(page.locator('.service-card')).toHaveCount(6)
  await expect(
    page.locator('.service-card').filter({ hasText: '游戏服务器' }).getByRole('link', { name: '打开服务' }),
  ).toHaveCount(0)
  await expect(
    page.locator('.service-card').filter({ hasText: '代码仓库' }).getByRole('link', { name: '打开服务' }),
  ).toHaveAttribute('href', 'https://git.example.com/')
  await page.screenshot({ path: info.outputPath('home-desktop.png'), fullPage: true })
  await page.getByRole('textbox', { name: '搜索服务' }).fill('开发服务器')
  await expect(page.locator('.service-card')).toHaveCount(1)
  await page.getByRole('textbox', { name: '搜索服务' }).fill('')
  await page.getByRole('button', { name: '只看收藏' }).click()
  await expect(page.locator('.service-card')).toHaveCount(2)
  expect(external).toEqual([])
  expect(errors).toEqual([])
})
test('CRUD and validation do not reload the document', async ({ page }, info) => {
  await page.goto('/config')
  await expect(page.getByRole('button', { name: '新增代理', exact: true })).toBeVisible()
  const timeOrigin = await page.evaluate(() => performance.timeOrigin)
  await page.screenshot({ path: info.outputPath('proxies-desktop.png'), fullPage: true })
  await page.getByRole('button', { name: '新增代理', exact: true }).click()
  await page.getByRole('button', { name: '保存配置', exact: true }).last().click()
  await expect(page.getByText('请填写代理名称', { exact: true })).toBeVisible()
  await fillProxy(page, 'e2e-service', '18888')
  await page.getByRole('textbox', { name: '分组', exact: true }).fill('本地测试')
  await page.screenshot({ path: info.outputPath('proxy-drawer.png'), fullPage: true })
  await page.getByRole('button', { name: '保存配置', exact: true }).last().click()
  await expect(page.locator('.n-drawer')).toHaveCount(0)
  let row = page.locator('tr').filter({ hasText: 'e2e-service' })
  await expect(row).toHaveCount(1)
  await row.getByRole('button', { name: '编辑', exact: true }).click()
  await page.getByRole('textbox', { name: '显示名称', exact: true }).fill('编辑后的服务')
  await page.getByRole('button', { name: '保存配置', exact: true }).last().click()
  await expect(row).toContainText('编辑后的服务')
  await row.getByRole('button', { name: '复制', exact: true }).click()
  await expect(page.getByRole('textbox', { name: '代理名称', exact: true })).toHaveValue('e2e-service-copy')
  await page.getByLabel('远程端口', { exact: true }).fill('18889')
  await page.getByRole('button', { name: '保存配置', exact: true }).last().click()
  await expect(page.locator('tr').filter({ hasText: 'e2e-service-copy' })).toHaveCount(1)
  await page.getByRole('button', { name: '新增代理', exact: true }).click()
  await fillProxy(page, 'e2e-service', '18890')
  await page.getByRole('button', { name: '保存配置', exact: true }).last().click()
  await expect(page.getByText('请使用不同的代理名称')).toBeVisible()
  await page.getByRole('button', { name: '关闭编辑抽屉' }).click()
  await page.getByRole('button', { name: '放弃修改', exact: true }).click()
  row = page.locator('tr').filter({ hasText: 'e2e-service-copy' })
  await row.getByRole('button', { name: '删除', exact: true }).click()
  await page.getByRole('button', { name: '确认删除', exact: true }).click()
  await expect(row).toHaveCount(0)
  expect(await page.evaluate(() => performance.timeOrigin)).toBe(timeOrigin)
})
test('save-and-continue keeps drawer open and resets name', async ({ page }) => {
  await page.goto('/config')
  await page.getByRole('button', { name: '新增代理', exact: true }).click()
  await fillProxy(page, 'continue-test', '18900')
  await page.getByRole('button', { name: '保存并继续添加', exact: true }).click()
  await expect(page.getByRole('textbox', { name: '代理名称', exact: true })).toHaveValue('')
  await expect(page.getByRole('textbox', { name: '本地地址', exact: true })).toHaveValue('127.0.0.1')
  await page.getByRole('button', { name: '关闭编辑抽屉' }).click()
  await expect(page.locator('.n-drawer')).toHaveCount(0)
})
test('settings persist, apply is disabled and logs are readable', async ({ page }) => {
  await page.goto('/settings')
  await expect(page.locator('.settings-panel .stat-icon')).toHaveCSS('width', '48px')
  await page.getByRole('textbox', { name: '目标地址' }).fill('test.example.com')
  await page.getByRole('button', { name: '保存地址', exact: true }).click()
  await expect(page.getByText('访问地址已保存，无需重启 frpc')).toBeVisible()
  await expect(page.getByRole('button', { name: '应用配置', exact: true })).toBeDisabled()
  await page.reload()
  await expect(page.getByRole('textbox', { name: '目标地址' })).toHaveValue('test.example.com')
  await page.getByRole('link', { name: '运行日志', exact: true }).click()
  await expect(page.getByLabel('日志内容')).toContainText('fixture log only')
})
test('mobile navigation and drawer fit viewport', async ({ page }, info) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/')
  await expect(page.locator('.service-card')).toHaveCount(6)
  await page.screenshot({ path: info.outputPath('home-mobile.png'), fullPage: true })
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(390)
  await page.getByRole('button', { name: '打开导航' }).click()
  await page.getByRole('link', { name: /代理管理/ }).click()
  await page.getByRole('button', { name: '新增代理', exact: true }).click()
  await expect(page.getByRole('textbox', { name: '代理名称', exact: true })).toBeVisible()
  await page.screenshot({ path: info.outputPath('drawer-mobile.png'), fullPage: true })
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(390)
})

test('concurrent edits reject stale saves and preserve the entered values', async ({ page, context }) => {
  await page.goto('/config')
  await page
    .locator('tr')
    .filter({ hasText: 'nas-web' })
    .getByRole('button', { name: '编辑', exact: true })
    .click()
  await page.getByRole('textbox', { name: '显示名称', exact: true }).fill('尚未保存的编辑')
  const other = await context.newPage()
  await other.goto('/settings')
  await other.getByRole('textbox', { name: '目标地址' }).fill('updated.example.com')
  await other.getByRole('button', { name: '保存地址', exact: true }).click()
  await expect(other.getByText('访问地址已保存，无需重启 frpc')).toBeVisible()
  await page.getByRole('button', { name: '保存配置', exact: true }).last().click()
  await expect(page.getByText(/配置已被其他页面或程序修改/)).toBeVisible()
  await expect(page.getByRole('textbox', { name: '显示名称', exact: true })).toHaveValue('尚未保存的编辑')
  await other.close()
})
